### ISSUE TITLE
创建脚手架的一些问题

### ISSUE THREAD

**Issue by HotPotAndMe** [shanbay/gobay#102]
背景是master分支
在创建脚手架前，其他依赖已经安装完毕
创建脚手架后出现了出现了两个问题
1. 在生成的代码
``` golang
\\ app\extensions.go
func GetApmCache(ctx context.Context) *cachext.CacheExt {
	return Cache.WithContext(ctx)
}
``` 
显示Cache没有WithContext()方法，进入源代码之后也没有找到
2. 没有生成gen文件夹，如文档所述，脚手架生成后应生成一个gen文件夹，其中也有一些api供外部调用

**Comment by HeathLee** [comment]
@gukz
