### ISSUE TITLE
provide an example 

### ISSUE THREAD

**Issue by himalkaya** [shanbay/gobay#176]
I am looking for a new dev platform using golang/orm/grpc so I am coming over ent. to gobay;  so I would like to see an example like this https://youtu.be/3iz9aM1AlGA (https://docs.servicestack.net/servicify) thereby using gobay as backend  and flutter as frontend, since flutter runs without any change on web/mobile/desktop.

**Comment by nicholasxuu** [comment]
Take a quick look at the updated quickstart guide?
https://github.com/shanbay/gobay/tree/master/docs
